version: '3'
services:
  java-app:
    build:
      context: JavaFuseBox/
    volumes:
      - data_volume:/opt/docker_project/boxfuse-sample-java-war-hello/
  
  tomcat:  
    build: ./Core
    volumes:
      - .target/hello-1.0.war:/opt/tomcat/webapps/hello-1.0.war
    ports:
      - '8080:8080'

volumes:
  data_volume: