version: '3'
services:
  maven:
    image: maven:3.3-jdk-8
    volumes: 
      - prod:/usr/src/prod
    command: > 
        bash -c "mvn clean install
        && cp target/*.war /usr/src/prod"
  tomcat:
    image: tomcat:alpine
    volumes:
      - prod:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
volumes:
  prod: