version: '3'
services:
  maven:
    image: ubuntu:20.04
    volumes: 
      - prod:/usr/src/prod
    command: > 
        bash -c "git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        && mvn package -f boxfuse-*/
        && cp target/*.war /usr/src/prod"
  tomcat:
    image: tomcat:alpine
    volumes:
      - prod:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
volumes:
  prod: