version: '3'
services:
  java-app:
    build:
      context: JavaFuseBox/
    volumes:
      - warnik:/opt/docker_project/boxfuse-sample-java-war-hello/target/hello-1.0.war

  tomcat:  
    build: ./Core
    volumes:
      - ./warnik:/opt/tomcat/webapps/hello-1.0.war
    ports:
      - '8080:8080'

volumes:
  warnik: