version: '3.3'
services:

  appbuilder:
    build:
      context: Java-Hello-Docker/
  web:
    build: .
    depends_on:
      - appbuilder
    volumes:
      - /opt/docker_project/boxfuse-sample-java-war-hello/target/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war
    ports:
      - '8080:8080'


# version: '3.8'

# services:
#   building:
#     build:
#       context: JavaFuseBox/
  
#   web:
#     depends_on:
#       - building
#     image: /opt/tomcat
#     volumes:
#       - /opt/docker_project/boxfuse-sample-java-war-hello/target/hello-1.0.war:/opt/tomcat/webapps/hello-1.0.war
#     ports:
#       - '8080:8080'