version: '3'
services:
  java-app:
    build:
      context: JavaFuseBox/
    volumes:
      - myapp:/home/node/app
  
  tomcat:  
    build: ./Core
    # volumes:
    #   - data_volume/hello-1.0.war:/opt/tomcat/webapps/hello-1.0.war
    ports:
      - '8080:8080'

volumes:
  myapp: