version: '3.8'

services:
  building:
    build:
      context: JavaFuseBox/
  
  web:
    depends_on:
      - building
    image: tomcat
    volumes:
      - ./target/hello-1.0.war:/opt/tomcat/webapps/hello-1.0.war
    ports:
      - '8080:8080'