version: '3.3'
services:
  java-app:
    build:
      context: JavaFuseBox/
    # volumes:
    # - data_volume:/var/www/data

  tomcat:
    container_name: tomcat-container
    build: ./tomcat_launcher
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    expose:
      - "8080"

# RUN cp boxfuse-*/target/*.war /usr/local/tomcat/webapps/

# version: '2'
# Services:
# web:
# container_name: web
# image: nginx
# ports:
# - "80:8080"
# volumes:
# - data_volume:/var/www/data
# app:
# container_name: app1
# build:
# context: .
# dockerfile: Dockerfile
# volumes:
# - data_volume:/data/app1/context
# volumes:
# data_volume: