version: '3.3'
services:
  httpd:
    container_name: httpd-container
    build: ./docker/httpd
    ports:
      - "80:80"
  tomcat:
    container_name: tomcat-container
    build: ./docker/tomcat
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    expose:
      - "8009"









# version: '3.8'

# services:
#   building:
#     build:
#       context: JavaFuseBox/
  
#   web:
#     depends_on:
#       - building
#     image: /opt/tomcat
#     volumes:
#       - /opt/docker_project/boxfuse-sample-java-war-hello/target/hello-1.0.war:/opt/tomcat/webapps/hello-1.0.war
#     ports:
#       - '8080:8080'